version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_bd
    environment:
      MYSQL_ROOT_PASSWORD: 40781889
      MYSQL_DATABASE: noticias
    volumes:
      - mysql_data:/var/lib/mysql
      - "./bd noticias.sql:/docker-entrypoint-initdb.d/noticias.sql"
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    container_name: backend_node
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 40781889
      DB_NAME: noticias
    ports:
      - "3001:3001"
    depends_on:
      - mysql

volumes:
  mysql_data:
